% Document settings, side mirror -----------------------------------------------

\documentclass[a4paper,					% Paper format
DIV=12,
11pt,									% Font size
% BCOR=8mm,								% Extra indent for binding correction
headsepline,							% Line below header
listof=totocnumbered,					% Numbering the Table of Content title
onecolumn,								% Document with two columns
%abstract=true,							% Showing Abstract title above the abstract
captions=tableheading,
titlepage=firstiscover,
onesided,
numbers=noenddot]{scrartcl}				% Do not reserve whole page for the cover

% \unsettoc{toc}{onecolumn}				% Print table of contents in two columns

\usepackage{setspace}					% Packages, which allows to set line spacing
\onehalfspacing							% Lines are spaced 1.5-fold
\setlength{\columnsep}{0.5cm}			% Space between columns in twocolumned document
\setlength{\parindent}{0pt}

\usepackage{cuted}						% Onecolumn contentnin twocolumned document


% Header and footer settings of the document -----------------------------------

\usepackage[automark]{scrlayer-scrpage}

\clearscrheadfoot						% Clear header and footer to provide space for customized content

\rehead[]{Data Science with R}
\rohead[]{Exercise 4}
\cehead[]{\today}
\cohead[]{\today}
\lehead[]{Exercise 4}
\lohead[]{Data Science with R}

\lefoot[]{\oldstylenums{\pagemark}}
\refoot[]{\textsc{{\small Raphael Schleutker}}}
\rofoot[]{\oldstylenums{\pagemark}}
\lofoot[]{\textsc{{\small Raphael Schleutker}}}


% Formation of the title page entries --------------------------------------------

\setkomafont{titlehead}{\centering}	% Show title head in small emphazised letters, centered

%\setkomafont{paragraph}{\normalfont\large\itshape}


\usepackage{tikz}
\usepackage{pgffor}
\usetikzlibrary{intersections,
decorations.pathmorphing,
shadows}

\tikzset{every picture/.style={/utils/exec={\sffamily}, text=black!80},
font={\fontsize{10pt}{12}\selectfont},
coord/.style={line width=.4mm, draw=black!80},
line/.style={line width=.2mm, draw=black!70}}

\usepackage{wrapfig}

\usepackage{seqsplit}


% Extra packages for language / characters, language settings --------------------

\usepackage[utf8]{inputenc}				% Unicode transformation format für Input
\usepackage[T1]{fontenc}				% Zeichensatzkodierung
\usepackage{lmodern}
\usepackage{upgreek}					% Providing non-emphasized greek letters
\usepackage{textcomp}					% Providing special characters 
\usepackage[english]{babel}				% Setting 'english' as the documents language
\usepackage{csquotes}


% Extra packages for math, special math characters etc., chemistry formulas -----------------

\usepackage{mathtools}
\usepackage{amssymb}					% Provides mathematical symbols
\usepackage{amstext}					% Provides \text{...} command in math environments
\usepackage{wasysym}					% Provides additional symbols like female, male, ...
\usepackage{amsthm}
\usepackage{thmtools}
%\usepackage{txfonts}
\usepackage{thm-restate}

%\newcommand{\bmmax}{2}
\usepackage{bm}

\newcommand{\matr}[1]{\bm{#1}}
\DeclareMathOperator*{\sums}{\sum\dots\sum}

\declaretheoremstyle[
bodyfont=\normalfont,
notefont=\normalfont\itshape,
spaceabove=12pt,
spacebelow=12pt,
postheadspace=9pt
]{mystyle}

\declaretheorem[name=Definition, numberwithin=section, style=mystyle]{definition}
\declaretheorem[name=Satz, sibling=definition, style=mystyle]{theorem}
\declaretheorem[name=Beispiel, sibling=definition, style=mystyle]{example}
\declaretheorem[name=Korollar, sibling=definition, style=mystyle]{corollar}
\declaretheorem[name=Folgerung, sibling=definition, style=mystyle]{implication}
\declaretheorem[name=Bemerkung, sibling=definition, style=mystyle]{remark}
\declaretheorem[name=Lemma, sibling=definition, style=mystyle]{lemma}
\declaretheorem[name=Behauptung, sibling=definition, style=mystyle]{claim}

\declaretheorem[
  style=mystyle,
  name=Beispiel \protect\continuation,
  unnumbered,
]{excont}

\newcommand{\continuation}{}
\newenvironment{continueexample}[2]
 {\renewcommand{\continuation}{#1}\excont[#2]}
 {\endexcont}
%\declaretheorem[name=Beweis, numbered=no]{proof}
%\declaretheorem[name=Beispiel, shaded={rulecolor=gray, rulewidth=1pt, bgcolor=white}]{example}

\newcommand{\mse}{\mathrm{MSE}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\Kov}{\mathrm{Kov}}
\newcommand{\E}{\mathrm{E}}
\newcommand{\Exp}{\mathrm{Exp}}
\newcommand{\Erl}{\mathrm{Erl}}


% Defining units for use in text ------------------------------------------------------------

\usepackage{siunitx}					% Package, which provides pssibility to easy use units in text

\sisetup{
output-decimal-marker = {,},			% Decimal parker is '.'
separate-uncertainty = true,
per-mode = symbol,						% 'per' is shown as a symbol (fraction like)
list-final-separator = { und },			% Lists end with an ', and'
list-pair-separator = { und },			% Lists with two entries use 'and' for separation
range-phrase = { bis },					% Numbers in ranges are separated with 'to'
exponent-product = \cdot				% Use dot as multiplication sign
}


% Extra packages for showing / including graphics -------------------------------------------

\usepackage{graphicx}					% Package, which allows to include graphics


% Extra packages for additonal functionalities (list of abbreviations, ...) ------------------

\usepackage[printonlyused]{acronym}		% Abbreviations
\usepackage[super]{nth}


% Extra packages for table formatting --------------------------------------------------------

\usepackage{booktabs}					% Providing better formatted lines for tables
%\usepackage{array}						% 
\usepackage{longtable}					% Allows to create multisided tables
\usepackage{threeparttable}				% Special environment which provides table footnotes
\usepackage{tabularx}					% Specify width of the tables independently of the content
\usepackage{multirow}

\usepackage{etoolbox}
\AtBeginEnvironment{tabular}{\small}
\AtBeginEnvironment{tabularx}{\small}
\AtBeginEnvironment{tablenotes}{\footnotesize}



% Extra packages for lists --------------------------------------------------------------------

\usepackage{enumitem}					% Provides additonal bullets for lists
\setitemize{itemsep=-3pt}
\setenumerate{itemsep=-3pt}


% Everything for references, citations, etc... ------------------------------------------------

\usepackage[backend=biber,				% Use biber to compile the references
natbib=true,							% Use natbib for scientific style
citestyle=numeric-comp,					% Citation style in text
bibstyle=numeric,						% Citation style in references
uniquename=init,						% 
sorting=none,							% Citations in the bibliography are sorted for appearance, not alphabetically
maxcitenames=2,
maxbibnames=5,
giveninits=true]{biblatex}				% Show just initiales of first name

\addbibresource{literature/literature.bib}	% Define path to the literature resource file

\renewcommand{\bibfont}{\small}			% Reference font size

\DeclareNameAlias{sortname}{last-first}							% Show last name first
\DeclareNameAlias{default}{last-first}							% Show last name first
\DeclareFieldFormat[article]{volume}{\mkbibbold{#1}}			% Show 'volume' in bold font
\renewcommand*{\mkbibnamefamily}[1]{\textsc{#1}}				% Show last name in small caps
\renewcommand*{\labelnamepunct}{\mkbibbold{\addcolon\space}}	% Show colon after authors and year instead of a dot

\usepackage{xpatch}
\xpretobibmacro{bbx:editor}{\mkbibbold\bgroup}{}{}
\xapptobibmacro{bbx:editor}{\egroup}{}{}

\DefineBibliographyStrings{english}{	% Define language for the bibliography
andothers={\emph{et\ al\adddot}},		% Write "et al." instead of "and others"
%pages={},								% Do not show 'pages' but just the site numbers
in={}									% Do not show 'in' but only the journal name
}

\AtEveryBibitem{\clearfield{month}}		% Remove field 'month' from entries
\AtEveryBibitem{\clearfield{issn}}		% Remove field 'issn' from entries
%\AtEveryBibitem{\clearfield{number}}	% Remove field 'number' from entries (often misused for issue)
\AtEveryBibitem{\clearfield{doi}}		% Remove field 'doi' from entries (link to paper is shown instead)

\AtEveryBibitem{						% If enrty type is 'article' or 'Article', remove the field 'urldate'
  \ifentrytype{article}{
  }{
    \clearfield{urldate}
    \clearfield{eprint}
  }
  \ifentrytype{Article}{
  }{
    \clearfield{urldate}
    \clearfield{eprint}
  }
  \ifkeyword{Review}{\tikz\filldraw[color=gray] (0,0) circle (2.5pt);}{}
  \ifkeyword{Tool}{\tikz\filldraw[color=gray] (0,0) -- (6pt,0) -- (3pt,6pt);}{}
}


% Defining extra colours for use --------------------------------------------------------------

\usepackage{xcolor}						% Package, which allows to define new colours

\definecolor{textgray}{RGB}{101 101 101}
\definecolor{darkwhite}{RGB}{252 252 252}
\definecolor{darkgray}{RGB}{68 68 68}

% Formatting captions ------------------------------------------------------------------------

\usepackage{caption}									% Show single line caption like multiline caption
\captionsetup{
format=plain,
belowskip=6pt,
aboveskip=6pt}

\renewcaptionname{english}{\figureautorefname}{\textsc{Figure}}	% 'Figure' is written in small caps when using autoref
\renewcaptionname{english}{\tableautorefname}{\textsc{Table}}	% 'Table' is written in small caps when using autoref
\addtokomafont{captionlabel}{\scshape}							% Writing 'Figure' and 'Table' in small caps
\addtokomafont{captionlabel}{\small}							% Size of the caption label
\addtokomafont{caption}{\small}									% Size of the caption

\usepackage{subcaption}
\captionsetup[subfigure]{labelfont=sc}
\captionsetup[sub]{
position=top,
font=footnotesize,
labelfont={sc},
labelformat=parens,
skip=3pt,
singlelinecheck=false
}

\renewcommand\thesubfigure{\textsc{\alph{subfigure}}}	% Referenced subfigures are shown in small caps in the text
\renewcommand\thesubtable{\textsc{\alph{subtable}}}		% Referenced subtables are shown in small caps in the text


% Hyperref -----------------------------------------------------------------------------------

\usepackage[colorlinks,
linkcolor = textgray,
citecolor = textgray,
filecolor = textgray,
urlcolor = textgray,
bookmarks=true,
bookmarksnumbered=true,
]{hyperref}

%\hypersetup{draft}

\hypersetup{pdftitle={Statistik II},
pdfauthor={Raphael Schleutker}}

\usepackage{bookmark}

\usepackage{blindtext}

% ---------------------------------------------------------------------
% ---------------------------------------------------------------------

\begin{document}

%!Rnw weave = knitr
%\SweaveOpts{concordance=TRUE}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
options(formatR.arrow = TRUE, width = 50, scipen=999)
opts_chunk$set(echo = TRUE,
               message = FALSE,
               warning = FALSE,
               fig.path = 'figures/graphics-',
               cache.path = 'cache/graphics-',
               fig.align = 'center',
               dev = 'pdf',
               fig.show = 'hold',
               par = FALSE,
               cache = FALSE,
               size = 'small',
               comment = '#')

opts_knit$set(self.contained=FALSE)

knit_hooks$set(par = function(before, options, envir) {
  if (before && options$fig.show!='none') {
    par(mar = c(4,4,.1,.1),
        cex.lab = .95,
        cex.axis = .9,
        mgp = c(2,.7,0),
        tcl = -.3)
  }
}, crop=hook_pdfcrop)

Sys.setenv(LANG = "en")
@

<<figure_settings, echo=FALSE>>=
library(ggplot2)

theme_set(theme_bw(base_size = 8))
@


\section*{Exercise 1}

R comes along with a lot of sample datasets. A very popular one is called \texttt{iris}, which holds sepal and petal measurements for different iris sub-species. The dataset is directly available to you by the variable name \texttt{iris}.

\begin{itemize}
	\item Look at the first and last few observations in the dataframe to get a first idea about the structure of the data.
	\item Calculate summary statistics for each of the columns.
	\item Calculate summary statistics for each of the sub-species separately.\\
	(\textit{Hint: You can use double brackets to extract an element from a list: \texttt{list\_with\_data[[1]]} returns the first element of the list.})
	\item You can plot each column combination of a dataframe by using the \texttt{plot} function. Do this. What do you see? Can you identify patterns?
\end{itemize}


\section*{Exercise 2}

Think back to the example with the fluorescence intensity at tricellular junctions from the presentation. Usually, one would not measure a single intensity value from one embryo but rather several values at different TCJ. If you view the experiment like this, what is the observational unit now? Look at the following tables. How are they wrongly formatted? What would they have to look like instead?

\begin{table}[h!]
\begin{tabular}{llllll}
\toprule
TCJ		&	Stage	&	Genotype	&	Embryo 1	&	Embryo 2	&	Embryo 3	\\
\midrule
1		&	14		&	y w			&	1.24		&	1.91		&	0.86	\\
2		&	14		&	M6[W186*]	&	0.23		&	0.97		&	0.38	\\
3		&	14		&	y w			&	0.98		&	1.35		&	0.22	\\
\vdots	&	\vdots	&	\vdots		&	\vdots		&	\vdots		&	\vdots	\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[h!]
\begin{tabular}{llll}
\toprule
Embryo	&	Stage	&	Genotype	&	Intensity Enrichment	\\
\midrule
1		&	14		&	y w			&	1.24, 1.91, 0.86, 0.55, \dots	\\
2		&	14		&	M6[W186*]	&	0.23, 0.97, 0.38, 1.06, \dots	\\
\vdots	&	\vdots	&	\vdots		&	\vdots	\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[h!]
\begin{tabular}{ll}
\toprule
Embryo			&	Intensity Enrichment	\\
\midrule
14/yw			&	1.24	\\
15/yw			&	0.23	\\
15/M6[W186*]	&	1.92	\\
14/M6[W186*]	&	1.73	\\
\vdots			&	\vdots	\\
\bottomrule
\end{tabular}
\end{table}

\pagebreak

\section*{*Exercise 3}

\emph{This exercise is for the upcoming lecture to prepare you for the content or to sensibilize you for a certain aspect.}\\
We will see in the next lecture how we can extract specific values from vectors and lists. One way to do this is to use square brackets \texttt{[i]} or double square brackets \texttt{[[i]]} where \texttt{i} is the position of the element we'd like to extract. Create a list like below and use these two ways to extract each of the elements separately. Do you see a difference for single and double brackets? Look carefully and use \texttt{str} to analyze the result.

<<>>=
sample_list <- list(1:10, mean, list(10:1, median))
@


\end{document}