\documentclass[10pt]{beamer}

\usetheme[progressbar=frametitle]{metropolis}
\usepackage{appendixnumberbeamer}

\usepackage{booktabs}
\usepackage[scale=2]{ccicons}

\usepackage{xspace}
\newcommand{\themename}{\textbf{\textsc{metropolis}}\xspace}

\usepackage[utf8]{inputenc}				% Unicode transformation format für Input
\usepackage[T1]{fontenc}				% Zeichensatzkodierung
\usepackage{lmodern}
\usepackage{upgreek}					% Providing non-emphasized greek letters
\usepackage{textcomp}					% Providing special characters 
%\usepackage[english]{babel}				% Setting 'english' as the documents language
\usepackage{csquotes}

\usepackage{ulem}

\usepackage{fontspec}
\usepackage{fontawesome}

\metroset{block=fill}

\usepackage{dirtree}

\title{Data Science with R}
\subtitle{Part I: Introduction and Command Line}
% \date{\today}
\date{February 21, 2020}
\author{Raphael Schleutker}
\institute{\textit{The most important thing in the programming language is the name. A language will not succeed without a good name. I have recently invented a very good name and now I am looking for a suitable language.}
\hfill --- Donald E. Knuth}
% \titlegraphic{\hfill\includegraphics[height=1.5cm]{logo.pdf}}

\usepackage{hyperref}

\begin{document}

%!Rnw weave = knitr
%\SweaveOpts{concordance=TRUE}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
options(formatR.arrow = TRUE, width = 50, scipen=999)
opts_chunk$set(echo = TRUE,
               message = FALSE,
               warning = FALSE,
               fig.path = 'figures/graphics-',
               cache.path = 'cache/graphics-',
               fig.align = 'center',
               dev = 'pdf',
               fig.show = 'hold',
               par = FALSE,
               cache = FALSE,
               size = 'small',
               comment = '#')

opts_knit$set(self.contained=FALSE)

knit_hooks$set(par = function(before, options, envir) {
  if (before && options$fig.show!='none') {
    par(mar = c(4,4,.1,.1),
        cex.lab = .95,
        cex.axis = .9,
        mgp = c(2,.7,0),
        tcl = -.3)
  }
}, crop=hook_pdfcrop)

Sys.setenv(LANG = "en")
@

<<figure_settings, echo=FALSE>>=
library(ggplot2)

theme_set(theme_bw(base_size = 8))
@



% *****************************************************************************
% TITLEPAGE
% *****************************************************************************

\maketitle

\begin{frame}{Table of contents}
  \setbeamertemplate{section in toc}[sections numbered]
  \tableofcontents[hideallsubsections]
\end{frame}


% *****************************************************************************
% ABOUT ME
% *****************************************************************************

%\section{About me}
%
%\begin{frame}[fragile]{About me}
%
%  \begin{columns}[T, onlytextwidth]
%    \column{.58\textwidth}
%  		{\large \textbf{Raphael Schleutker, M.Sc.}}
%  		
%  		\vspace{.25cm}
%  		
%  		\alert{\href{mailto:raphael.schleutker@uni-muenster.de}{raphael.schleutker@uni-muenster.de}}
%  		
%  		Badestra\ss{}e 9, 48149 Münster (at least sometimes)
%  	\column{.4\textwidth}
%  		\includegraphics[width=\textwidth]{figures/_DSC8779.jpg}
%  \end{columns}
%  
%  \vspace{.5cm}
%  
%  \begin{tabular}{lp{8cm}}
%  	2013--2016	&	Bachelor of Science Biosciences, University of Münster	\\
%  	2016--2018	&	Master of Science Molecular Biomedicine, University of Münster	\\
%  	2018--today	&	Bachelor of Science Statistics (Informatics), University of Dortmund	\\
%  	From 2019	&	PhD in the Group of Stefan Luschnig	\\
%  \end{tabular}
%  
%  \rightarrow \quad Creator and maintainer of the CRC 1348 website
%
%\end{frame}



% *****************************************************************************
% ORGANIZATIONAL STUFF
% *****************************************************************************

\section{Organizational Stuff}
% *****************************************************************************

\begin{frame}[fragile]{Contents of this workshop}
	
	\begin{enumerate}
		\item Introduction
		\item Primitive data structures and assignments
		\item Functions I and how to get help
		\item Non-primitive data structures
		\item Subsetting
		\item Data input/output
		\item Working with data frames
		\item Graphics I
		\item Control structures
		\item Working with text information
		\item Functions II
		\item Graphics II
		\item Functions III / Scoping rules
		\item Communicating results and outlook\\
		\vdots
	\end{enumerate}
	
\end{frame}


% =============================================================================


\begin{frame}[fragile]{Procedure of this workshop}
	
\begin{itemize}[<+- | alert@+>]
	\item We will meet weekly, if possible at the same time always.
	\item I will give a lecture on a specific topic.
	\item These lectures will build up on top of each other. So if you miss one week, you would have to work yourself through the lecture in order to keep track.
	\item Additionally, I will hand out weekly exercises. If you do them, you have good chances to learn something. If you don't do them, you will have no chance to learn anything (my personal experience).
	\item Each sheet will have some exercises from the last lecture and some informations/exercises for the upcoming lecture.
	\item The exercises will \emph{shortly} be discussed in our meetings. I will also upload sample solutions with explanations.
\end{itemize}
	
\end{frame}


% =============================================================================


\begin{frame}[fragile]{Where to get the material}
	
I will upload everything to github, a repository for shared development of code.
	
\end{frame}


% =============================================================================


\begin{frame}[fragile]{What other resources could you use?}
	
There are a lot of resource available for learning R like books, workshops, online tutorials, so called data camps.

\begin{itemize}[<+- | alert@+>]
	\item Some books are good for learning R, others are not. A good one is for instance \emph{The Art of R Programming}. Books that i read in the beginning of learning R and that I found nice these days are \emph{Hand-On Programming with R}, \emph{R for Data Science}, and \emph{Advanced R}. I do \emph{not} recommend these books cause they do not teach you R but how to use the packages written by the authors (the tidyverse packages including \emph{dplyr}, \emph{ggplot2}, \emph{tidyr}, etc.).
	\item The same applies to many online resources. Often, they show you how to use the tidyverse packages. This does \emph{not} replace a solid understanding of base R.
	\item As soon as you have acquired a certain understanding the best way to improve is practicing, recapitulating old code and reading source code from professional packages.
\end{itemize}
	
\end{frame}


% =============================================================================


%\begin{frame}[fragile]{What to do with the exercises}
%	
%	
%	
%\end{frame}



% *****************************************************************************
% ABOUT R
% *****************************************************************************

\section{About R}
% *****************************************************************************

\begin{frame}[fragile]{R - A programming language for statistics and graphics}
	
	There are several hundreds of different programming languages out there. What does qualify R to be learned by data scientists?
	
	\begin{itemize}[<+- | alert@+>]
		\item It was designed for statistics and graphics and therefore has many built-in functions that are only available as third-party packages in other languages.
		\item It is an interpreted language and therefore much easier to learn for beginners.
		\item It is completely free\dots
		\item It is heavily used by scientists and therefore many functionalities were developed for analyzing all kinds of biological data.
		\item It comes with all the fun of programming \faSmileO
	\end{itemize}
	
\end{frame}


% =============================================================================


\begin{frame}[fragile]{R - A programming language for statistics and graphics}
	
	Cons about R include
	
	\begin{itemize}[<+- | alert@+>]
		\item R is considered slow. It is indeed not blazingly fast but fast enough for everything you will do. Also, R is often slow because the code was written by people that do not have a formal education in programming and that is therefor very inefficient.
		\item R is not a general purpose language. It is designed for statistics and graphics. If you discover the programmer within you and you want to write general software (like the database application I'm working on) you would have to learn another language.
		\item It does not have a graphical user interface (GUI). You will have to \emph{write} the code yourself and eventhough some IDEs like RStudio support you with GUI functionalities you still have to write that code into your script.
	\end{itemize}
	
\end{frame}


% =============================================================================


\begin{frame}[fragile]{R and RStudio}
	
	A common misconception arises from differentiating R and RStudio.
	
	\begin{itemize}[<+- | alert@+>]
		\item R is a programming language, a theoretical construct consisting of syntax and semantics. It comes along with an interpreter that interprets and translates your code into a machine readable form. Besides the standard interpreter others are available.
		\item RStudio is an integrated development environment (IDE) that should make the work with R as easy as possible. The editor in which you have written your code is of absolutely no importance (and thus should not be cited).
	\end{itemize}
	
\end{frame}


% =====================================================
% =====================================================


\section{Project Organization 101}

\begin{frame}[fragile]{How to structure your project on the computer}
	
	{\large \textbf{Some basic rules}}
	
	\begin{itemize}[<+- | alert@+>]
		\item Your project should be self-contained
		\item Use relative path descriptions
		\item Use a standardized naming convention for your files
		\item Never user spaces in file or folder names
		\item Avoid uppercase letters
		\item Do not mix up your raw data with analysis
		\item Document your project structure and what you have done
		\item Evaluate your behaviour regulary and think of what could be improved
	\end{itemize}
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Your project should be self-contained}
	
	\begin{block}{Self-containedness}
		As far as possible, all files of one project and only those should live within one folder. Do not spread project files around and do not mix them up with files/folders from other projects (or private stuff).
	\end{block}
	
	\textbf{Benefits}
	
	\begin{itemize}
		\item It is much easier to find everything.
		\item Your life will be much easier, if you have to migrate to a new computer.
		\item If your done, just drag the folder into an archive (zip, gzip, ...) and that's it.
	\end{itemize}
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Use relative path descriptions}
	
	\begin{block}{Relative path descriptions}
		A path description should never depend on the computer. Imagine a script file that lives in the root folder of your project and you want to refer to a file in the \texttt{data} subfolder.
		
		\sout{\texttt{C:/Users/Raphael/Documents/project\_a/data/raw/data.txt}}
		
		\texttt{./data/raw/data.txt}
	\end{block}
	
	\begin{itemize}
		\item \texttt{./} refers to the current location of the file.
		\item \texttt{../} refers to the parent folder in a folder hierarchy.
	\end{itemize}
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Use a standardized naming convention for your files}
	
	\begin{block}{Standardized naming convention}
		Files of the same type should have a common naming structure like \texttt{<yyyy-mm-dd>\_<genotype>\_<experimentID>.<extension>}. Choose a character as a separator between the information chunks (like underscores \texttt{\_}) and never use this character for anything else in your file and folder names.
	\end{block}
	
	Following this rule allows it to easily get the meta information saved in the file name with R or other programming languages. A typical procedure is to split the file name at every appearance of the separator. Then the first element is always the date, the second is always the genotype and so forth.
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Never user spaces in file or folder names}
	
	\begin{block}{Spaces}
		Spaces are a common source of ambiguity in programming code. But in contrast to humans programs do not try to guess what you could have meant but create an error instead. So please, do not use spaces.
	\end{block}
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Avoid uppercase letters}
	
	\begin{block}{Uppercase letters}
		Some programs differentiate between uppercase and lowercase letters and some do not. To avoid unexpected issues in your programs always use lowercase letters.
	\end{block}
	
<<error_selfcontainedness>>=
data <- c(1, 3.1, 4.67, 9, 32.98)
data
Data
@
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Do not mix up your raw data with analysis}
	
	\begin{block}{Raw data}
		Keep your raw data separated from any kind of analysis. Do not save your results along with your raw data in the same folder and never change your raw data.
	\end{block}
	
	This is of particular importance for everyone who's using excel. Well, what else can I say\dots
	
\end{frame}

% =====================================================

\begin{frame}[fragile]{Document your project structure and what you have done}
	
	\begin{block}{Documentation}
		I expect everyone here to be quite clever but no one can keep track of dozens, hundreds or even thousands of files. So create a README text file to document the folder structure and what kind of files each folder contains.
	\end{block}
	
\end{frame}

% =====================================================


\begin{frame}[fragile]{An example structure}
	
	\dirtree{%
		.1 patency\_index.
		.2 data.
		.3 microscopy.
		.4 20200-02-15\_aka\_m6-f.tiff.
		.4 \vdots.
		.2 output.
		.3 figure\_1.pdf.
		.2 src.
		.3 R.
		.4 utils.R.
		.4 graphics.R.
		.3 imagej.
		.4 measure\_cells.ijm.
		.2 analysis.R.
		.2 README.md.
	}
	
\end{frame}

% =====================================================


\begin{frame}[fragile]{Evaluate your behaviour regulary and think of what could be improved}
	
	\textbf{You steadily try to become a better biologist. Why not steadily trying to become a better data scientist as well?}
	
\end{frame}


\end{document}